// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPotionSubforum() {
  return window['go']['main']['App']['GetPotionSubforum']();
}

export function GetPotionThread() {
  return window['go']['main']['App']['GetPotionThread']();
}

export function GetTool() {
  return window['go']['main']['App']['GetTool']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function SubforumPotionsClub(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubforumPotionsClub'](arg1, arg2, arg3);
}

export function UpdatePotionSubforum(arg1) {
  return window['go']['main']['App']['UpdatePotionSubforum'](arg1);
}

export function UpdatePotionThread(arg1) {
  return window['go']['main']['App']['UpdatePotionThread'](arg1);
}
