// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {tool} from '../models';

export function GetConfig():Promise<config.Config>;

export function Login(arg1:string,arg2:string,arg3:boolean):Promise<tool.LoginResponse>;
