package potion

import "html/template"

// declare a map of potion names to potion icons
var PotionIcons = map[string]template.HTML{
	"Agudizadora del Ingenio":             `<img src="https://i.imgur.com/GanNYpr.png" class="tooltip" title="Agudizadora del Ingenio"/>`,
	"Amortentia":                          `<img src="https://i.imgur.com/yuVxqDZ.png" class="tooltip" title="Amortentia"/>`,
	"Antídoto de Glumbumble":              `<img src="https://i.imgur.com/9RBZCeu.png" class="tooltip" title="Antídoto de Glumbumble"/>`,
	"Antídoto para venenos comunes":       `<img src="https://i.imgur.com/0RRcrav.png" class="tooltip" title="Antídoto para Venenos Comunes"/>`,
	"Antídoto para Venenos Tóxicos":       `<img src="https://i.imgur.com/m2sCKZf.png" class="tooltip" title="Antídoto para Venenos Tóxicos"/>`,
	"Brebaje Parlanchín":                  `<img src="https://i.imgur.com/YHbpTZb.png" class="tooltip" title="Brebaje Parlanchín"/>`,
	"Crecepelo":                           `<img src="https://i.imgur.com/lcAX0qO.png" class="tooltip" title="Crecepelo"/>`,
	"Curadora de Furúnculos":              `<img src="https://i.imgur.com/lGHayif.png" class="tooltip" title="Curadora de Furúnculos"/>`,
	"Doxycida":                            `<img src="https://i.imgur.com/ACnnCYS.png" class="tooltip" title="Doxycida"/>`,
	"Elixir para inducir Euforia":         `<img src="https://i.imgur.com/qigGa6E.png" class="tooltip" title="Elixir para inducir Euforia"/>`,
	"Embellecedora":                       `<img src="https://i.imgur.com/CQSs7AL.png" class="tooltip" title="Embellecedora"/>`,
	"Esencia de Díctamo":                  `<img src="https://i.imgur.com/DaWtYLH.png" class="tooltip" title="Esencia de Díctamo"/>`,
	"Esencia de Murtlap":                  `<img src="https://i.imgur.com/TPPuHVj.png" class="tooltip" title="Esencia de Murtlap"/>`,
	"Felix Felicis":                       `<img src="https://i.imgur.com/o54Rv3c.png" class="tooltip" title="Felix Felicis"/>`,
	"Fertilizante de Estiércol de Dragón": `<img src="https://i.imgur.com/z7biKGy.png" class="tooltip" title="Fertilizante de Estiércol de Dragón"/>`,
	"Filtro de Muertos en Vida":           `<img src="https://i.imgur.com/HSFCLlF.png" class="tooltip" title="Filtro de Muertos en Vida"/>`,
	"Filtro de Paz":                       `<img src="https://i.imgur.com/Tm4fAWN.png" class="tooltip" title="Filtro de Paz"/>`,
	"Grasp of Death":                      `<img src="https://i.imgur.com/TA2nuNv.png" class="tooltip" title="Grasp of Death"/>`,
	"Multijugos":                          `<img src="https://i.imgur.com/1kEPEYJ.png" class="tooltip" title="Multijugos"/>`,
	"Pócima para Dormir":                  `<img src="https://i.imgur.com/Z7R6IF4.png" class="tooltip" title="Pócima para Dormir"/>`,
	"Poción Aliento de Fuego":             `<img src="https://i.imgur.com/JiZi0Wh.png" class="tooltip" title="Poción Aliento de Fuego"/>`,
	"Poción Calmante":                     `<img src="https://i.imgur.com/HTMjhyQ.png" class="tooltip" title="Poción Calmante"/>`,
	"Poción de Despertares":               `<img src="https://i.imgur.com/lfgDzmp.png" class="tooltip" title="Poción de Despertares"/>`,
	"Poción de Erumpent":                  `<img src="https://i.imgur.com/TzFgk4h.png" clas="tooltip" title="Poción de Erumpent"/>`,
	"Poción de la Memoria":                `<img src="https://i.imgur.com/ldkNgXk.png" class="tooltip" title="Poción de la Memoria"/>`,
	"Poción de la Risa":                   `<img src="https://i.imgur.com/rnrljbI.png" class="tooltip" title="Poción de la Risa"/>`,
	"Poción del Olvido":                   `<img src="https://i.imgur.com/qsTMBQd.png" class="tooltip" title="Poción del Olvido"/>`,
	"Poción Herbicida":                    `<img src="https://i.imgur.com/JE6nCfo.png" class="tooltip" title="Poción Herbicida"/>`,
	"Poción Herbovitalizante":             `<img src="https://i.imgur.com/FiunEWk.png" class="tooltip" title="Poción Herbovitalizante"/>`,
	"Poción Oculus":                       `<img src="https://i.imgur.com/0IXlBh8.png" class="tooltip" title="Poción Oculus"/>`,
	"Poción para el Dolor de Estómago":    `<img src="https://i.imgur.com/k3cFa0J.png" class="tooltip" title="Poción para el Dolor de Estómago"/>`,
	"Poción Pimentónica":                  `<img src="https://i.imgur.com/U5zJMuB.png" class="tooltip" title="Poción Pimentónica"/>`,
	"Poción Protectora contra las Llamas": `<img src="https://i.imgur.com/dx4Dh3y.png" class="tooltip" title="Poción Protectora contra las Llamas"/>`,
	"Poción Vigorizante":                  `<img src="https://i.imgur.com/V5mkB3V.jpg" class="tooltip" title="Poción Vigorizante"/>`,
	"Poción Volubilis":                    `<img src="https://i.imgur.com/U3SIfC6.png" class="tooltip" title="Poción Volubilis"/>`,
	"Solución Agrandadora":                `<img src="https://i.imgur.com/zWxv0P1.png" class="tooltip" title="Solución Agrandadora"/>`,
	"Solución Encogedora":                 `<img src="https://i.imgur.com/nO9UMLH.png" class="tooltip" title="Solución Encongedora"/>`,
	"Veritaserum":                         `<img src="https://i.imgur.com/29AFHVA.png" class="tooltip" title="Veritaserum"/>`,
	"Zumo de Mandrágora":                  `<img src="https://i.imgur.com/la020XU.jpg" class="tooltip" title="Zumo de Mandrágora"/>`,
}
